### PR TITLE
Hello rails

### PR DESCRIPTION
**Pull request by ChrispaixK**
# Hello-rails-backend
> Backend for hello rails-react app done in separated repositories

In this PR I : 
- Create a new rails API app with PostgreSQL as a backend
- Create a table to store different greetings in the database
- Create an API endpoint that selects a random greeting from the table 

## Note 🚨 
- Run the server on port 3001
  - In the terminal `rails s -p 3001`
- [Link to the front end part of the app](https://github.com/ChrispaixK/hello-react-front-end)

### CODE REVIEW

**Comment by sja-thedude** [comment]
Hi @ChrispaixK,

View this [here](https://github.com/ChrispaixK/hello-react-front-end/pull/1#issuecomment-1324108880)

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Invalid Code Review Request ❌

Hi @ChrispaixK, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, but do not have In the README file for the frontend, link to the Rails API (backend app). Make sure to add it. This is required. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by ChrispaixK** [comment]
oh thank you @sja-thedude !

**Review by HAMMAS-SALEEM — APPROVED** [review]
# Status: Approved :green_circle: :1st_place_medal: :100:
success

## Hey @ChrispaixK :wave:

Great work on implementing the requirements. Your project is complete. :blush:
There is nothing else to say about your project. :+1:


## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Linters
✔️ Following requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
